### PR TITLE
Fix 12 for phone icon (fix #12)

### LINKED ISSUE #12: Phone Favicon in footer reloads page
pls fix guy

### PR DESCRIPTION
**Pull request by JKirkYuan**
Removed all the href in pages for phone icon issue #12

### CODE REVIEW

**Comment by AveryVine** [comment]
Any chance that you could modify the script instead so that the whole things is clickable, including the icon? This will make only the text clickable

**Comment by JKirkYuan** [comment]
Yes

**Comment by JKirkYuan** [comment]
I feel like this should work. Can't test because I can't locally serve the web server

**Comment by AveryVine** [comment]
I'll give it a quick test

**Review by AveryVine — APPROVED** [review]

**Pull request merged**
